### ISSUE TITLE
Add Google Calendar Subscription

### ISSUE THREAD

**Issue by PRIEWIENV** [aegis-readers/aegis-readers.github.io#3]
Actually in #2 I wanted to suggest embedding a subscription of a public Google Calendar in the homepage. And in each announcement, the corresponding event can be embedded on it.

Refer to https://support.google.com/calendar/answer/37083?hl=en

**Comment by frostwing98** [comment]
Sure. I think you would like a calendar of all AEGIS events at home page of our blog. You can check http://aegis-readers.github.io/ now and see if it was what you sugested to be.
